#if !canImport(ObjectiveC)
import XCTest

extension CollectionExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CollectionExtensionsTests = [
        ("testIndicesWhere", testIndicesWhere),
        ("testMoveIndividual", testMoveIndividual),
        ("testMovePredicate", testMovePredicate),
        ("testMoveRange", testMoveRange),
        ("testMoveRangeSet", testMoveRangeSet),
        ("testNoCopyOnWrite", testNoCopyOnWrite),
        ("testRemoveAllRangeSet", testRemoveAllRangeSet),
    ]
}

extension RangeSetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RangeSetTests = [
        ("testInsertions", testInsertions),
        ("testIntersection", testIntersection),
        ("testInvariant", testInvariant),
        ("testRemovals", testRemovals),
        ("testSymmetricDifference", testSymmetricDifference),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CollectionExtensionsTests.__allTests__CollectionExtensionsTests),
        testCase(RangeSetTests.__allTests__RangeSetTests),
    ]
}
#endif
