#if !canImport(ObjectiveC)
import XCTest

extension CollectionExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CollectionExtensionsTests = [
        ("testDiscontiguousSliceSlicing", testDiscontiguousSliceSlicing),
        ("testGatherPredicate", testGatherPredicate),
        ("testGatherRangeSet", testGatherRangeSet),
        ("testIndicesWhere", testIndicesWhere),
        ("testNoCopyOnWrite", testNoCopyOnWrite),
        ("testRemoveAllRangeSet", testRemoveAllRangeSet),
        ("testShiftIndividual", testShiftIndividual),
        ("testShiftRange", testShiftRange),
    ]
}

extension RangeSetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RangeSetTests = [
        ("testContains", testContains),
        ("testInsertions", testInsertions),
        ("testIntersection", testIntersection),
        ("testInvariant", testInvariant),
        ("testRemovals", testRemovals),
        ("testSymmetricDifference", testSymmetricDifference),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CollectionExtensionsTests.__allTests__CollectionExtensionsTests),
        testCase(RangeSetTests.__allTests__RangeSetTests),
    ]
}
#endif
