name: Validate Swift project proposals with swift-evolution-metadata-extractor

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
    paths:
      - 'proposals/*'

jobs:
  validate:
    name: Validate Proposals
    uses: swiftlang/github-workflows/.github/workflows/proposal_validation.yml@0.0.13
    with:
      project: "swift"
